#!/usr/bin/env bash

# NORMCORE
# ========
# Downloads `normalize.css` by Nicolas Gallagher (github/necolas)
#
# Copyright (c) 2014, Aaron Greenberg

BASENAME="normalize.css"
CURL=`which curl`
PATH="`pwd`";
VERSION="latest"

# Cause exit if a command fails.
set -o errexit

# Usage
read -r -d '' usage <<-'EOF'
  Usage: normcore [options] PATH
  -s|--sass               Downloads normalize.css as _normalize.scss.
  -v|--version VERSION    normalize.css version to download. Default 'latest'.
  -h|--help               Print this message.
EOF

while :; do

  if test -d "$1"; then
    PATH="$1"
  fi

  case "$1" in
    -s|--sass) BASENAME="_normalize.scss" ;;

    -v|--version)
      if test "$2"; then
        VERSION="$2"
        shift 2
        continue
      else
        echo 'ERROR: Must specify a version number!' > &2
        exit 1
      fi
      ;;
    --version=?*) VERSION="${1#*=}" ;;
    --version=)
      echo 'ERROR: Must specify a version number!' > &2
      exit 1
      ;;

    -h|--help) echo "${usage}" && exit 0 ;;

    *) break
  esac

  shift
done

if ! test "${PATH}" = "*/"; then
  PATH="${PATH}/"
fi

NORMALIZE_URL="http://necolas.github.io/normalize.css/${VERSION}/normalize.css"

${CURL} -fsSL "${NORMALIZE_URL}" > ${PATH}${BASENAME}
